In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import linear_model

In [2]:
data=pd.read_csv('Downloads/hiring.csv')
data

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

Filling blank test score with median value

In [3]:
test_score_med=data.test_score.median()


In [31]:
data.test_score=data.test_score.fillna(test_score_med)
data

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [30]:
data.experience=data.experience.fillna('zero')
data

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [5]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [32]:
from word2number import w2n
data.experience=data.experience.apply(w2n.word_to_num)
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [33]:
reg=linear_model.LinearRegression()
reg.fit(data[['experience','test_score','interview_score']],data.salary)

LinearRegression()

In [35]:
reg.predict([[2,9,6]])

/Users/richajoshi/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [36]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [37]:
reg.intercept_

17737.26346433768

In [38]:
2*2812.95487627+9*1845.70596798+6*2205.24017467+17737.26346433768

53205.967976717686

In [40]:
reg.predict([[12,10,10]])

/Users/richajoshi/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])